# Changes here will be overwritten by Copier
_commit: fa27c8d
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: js
add_wiki: false
email: 3105306+timkpaine@users.noreply.github.com
github: nbprint
project_description: A framework for customizing NBConvert templates and building
    reports
project_name: nbprint
python_version_primary: '3.9'
team: the nbprint authors
