---
debug: false
pagedjs: true
_target_: nbprint.Configuration
outputs:
  _target_: nbprint.HTMLOutputs
  path_root: ./outputs

page:
  size: [8.5, 1000]

content:
  - _target_: nbprint.ContentCode
    content: |
      from superstore import superstore
      df = superstore()
      for i in range(100):
        print(df)
