---
# global config options
css: ".jp-RenderedHTMLCommon h1, .jp-RenderedHTMLCommon h2, .jp-RenderedHTMLCommon h3, .jp-RenderedHTMLCommon h4, .jp-RenderedHTMLCommon h5, .jp-RenderedHTMLCommon h6 { margin: 0 !important; }"
debug: false
# end global config options

resources:

outputs:
  _target_:  nbprint.NBConvertOutputs
  root: ./outputs
  target: "html"

parameters:
  _target_:  nbprint.example.ExampleFinanceParameters
  ticker: "ABCD"
  company_name: "ABCD Inc."
  sector: "Autos & Shared Mobility"
  region: "North America"
  country: "United States of America"
  color: "#5db39c"

  rating: Overweight
  view: In-Line
  price_target: 10.0

context:
  _target_:  nbprint.example.ExampleFinanceContext

page:

content:
  - _target_:  nbprint.example.ExampleFinanceTitle
    title: "Jefferies Morgan"
    subtitle: "Research"
    date: "November 8, 2023 08:45 GMT"
    styles:
      - scope:
          element: div
          classname: row
        spacing:
          padding:
            bottom: 10
      - scope:
          element: h1
        text:
          font:
            family: sans-serif
            size: 25
        spacing:
          padding:
            right: 15
        border:
          right:
            width: 2
            style: solid
            color: black
      - scope:
          element: h2
        text:
          font:
            family: sans-serif
            size: 12
            transform: uppercase
            weight: bold
        spacing:
          padding:
            left: 15
      - scope:
          element: span
        text:
          font:
            size: 15
            style: italic
            color: grey

  - _target_:  nbprint.ContentFlexRowLayout
    sizes: [5, 3]
    content:
      - _target_:  nbprint.ContentFlexColumnLayout
        css: ":scope { border-right: 1px solid black; margin-right: 5px; }"
        content:
          - _target_:  nbprint.example.ExampleFinanceStockHeadline
            company_name: ${parameters.company_name}
            region: ${parameters.region}
            byline: "Solid Growth in both Domestic and International Markets"
            color: ${parameters.color}

          - _target_:  nbprint.example.ExampleFinanceStockPTUpdate
            rating: ${parameters.rating}
            view: ${parameters.view}
            price_target: ${parameters.price_target}

          - _target_:  nbprint.example.ExampleFinanceStockSubHeadline
            text: |
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.

      - _target_:  nbprint.ContentFlexColumnLayout
        content:
          - _target_:  nbprint.example.ExampleFinanceAuthor
            name: John Smith
            title: Equity Analyst
            email: John.Smith@jm.com
            phone: +1 212 867-5309
            color: ${parameters.color}

          - _target_:  nbprint.example.ExampleFinanceAuthor
            name: Jane Doe
            title: Equity Analyst
            email: Jane.Doe@jm.com
            phone: +1 212 867-5309
            color: ${parameters.color}

          - _target_:  nbprint.example.ExampleFinanceStockQuickStats
            color: ${parameters.color}
            ticker: ${parameters.ticker}
            company_name: ${parameters.company_name}
            sector: ${parameters.sector}
            country: ${parameters.country}

            rating: ${parameters.rating}
            view: ${parameters.view}
            price_target: ${parameters.price_target}

            share_price: 7.59
            market_cap: 1,024
            range_min: 4.35
            range_max: 8.25

          - _target_:  nbprint.example.ExampleFinanceStockEarningsTable

  - _target_:  nbprint.example.ExampleFinanceSectionHeading
    title: "Investment Thesis"
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      We initiate coverage of ABCD Inc. with an Overweight rating and a $10.00 price target,
      representing 32% upside from current levels. Our positive view is predicated on three key pillars:
      (1) strong secular tailwinds driving sustained growth in both domestic and international markets,
      (2) improving operational efficiency leading to margin expansion, and (3) a robust innovation
      pipeline that positions the company to capture incremental market share.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      The company has demonstrated remarkable execution over the past 18 months, delivering consistent
      revenue growth while simultaneously expanding margins. Management's strategic focus on high-growth
      segments, combined with disciplined capital allocation, has resulted in best-in-class returns on
      invested capital. We believe these trends are sustainable and see further upside as the company
      scales its operations.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Our financial models incorporate conservative assumptions around market share gains and pricing
      power. We project revenue to grow at a 14-16% CAGR through FY2026, with EBITDA margins expanding
      from 14.6% in FY2023 to 16.1% by FY2026. This translates to earnings growth significantly above
      industry averages, justifying a premium valuation multiple.

  - _target_:  nbprint.example.ExampleFinanceBulletPoints
    items:
      - "Market leadership in high-growth segments with 28% market share in North America"
      - "Strong brand recognition and customer loyalty driving repeat business"
      - "Vertically integrated supply chain providing cost advantages over competitors"
      - "Experienced management team with proven track record of value creation"
      - "Healthy balance sheet with net debt to EBITDA of 1.8x providing flexibility for M&A"

  - _target_:  nbprint.ContentPageBreak

  - _target_:  nbprint.example.ExampleFinanceSectionHeading
    title: "Company Overview"
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Founded in 2010, ABCD Inc. is a leading provider of innovative mobility solutions serving both
      consumer and commercial markets. The company operates through three primary business segments:
      Personal Mobility (52% of revenue), Fleet Solutions (31%), and Aftermarket Services (17%). With
      operations in 45 countries and a workforce of approximately 18,000 employees, ABCD has established
      itself as a key player in the rapidly evolving transportation ecosystem.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      The Personal Mobility segment focuses on direct-to-consumer sales of electric and hybrid vehicles
      designed for urban and suburban use. This segment has been the primary growth driver, benefiting
      from increasing consumer adoption of sustainable transportation alternatives. The Fleet Solutions
      segment provides comprehensive mobility packages to corporate clients and municipalities, including
      vehicle leasing, maintenance, and fleet management software. Aftermarket Services encompasses parts,
      accessories, and extended warranty offerings, generating highly profitable recurring revenue streams.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Geographically, North America accounts for 58% of revenues, with Europe contributing 28%, and
      emerging markets representing the remaining 14%. The company has been actively expanding its
      international footprint, with particular emphasis on high-growth markets in Southeast Asia and
      Latin America where urbanization trends and government incentives are driving adoption of
      sustainable mobility solutions.

  # Financial Analysis
  - _target_:  nbprint.example.ExampleFinanceSectionHeading
    title: "Financial Analysis & Outlook"
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      ABCD Inc. has demonstrated strong financial performance over the past three years, with revenue
      growing from $8.9 billion in FY2021 to $12.5 billion in FY2023, representing a compound annual
      growth rate of 18.5%. This growth has been driven by robust demand across all business segments,
      successful new product launches, and strategic market expansion initiatives. We expect this
      momentum to continue, projecting revenues of $14.1 billion in FY2024 and $18.7 billion by FY2026.

  - _target_:  nbprint.example.ExampleFinanceFinancialTable

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Profitability metrics have shown consistent improvement, with gross margins expanding from 34.2%
      in FY2021 to 36.6% in FY2023. This margin expansion reflects favorable product mix shifts toward
      higher-margin offerings, operational efficiencies gained through scale, and the company's ability
      to pass through cost inflation to customers. We anticipate further margin expansion to 37.6% by
      FY2026 as the company continues to optimize its cost structure and benefits from operating leverage.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Operating expenses as a percentage of revenue have declined from 27.8% in FY2021 to 26.0% in
      FY2023, demonstrating strong operational discipline. While the company continues to invest heavily
      in R&D and sales infrastructure to support growth, management has shown an ability to scale these
      investments efficiently. EBITDA margins have expanded from 12.3% to 14.6% over this period, and
      we project further improvement to 16.1% by FY2026.

  - _target_:  nbprint.example.ExampleFinanceKeyMetricsTable

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Free cash flow generation has been robust, with the company producing $820 million in FY2023,
      representing a conversion rate of 96% of net income. This strong cash generation supports the
      company's growth investments while maintaining balance sheet flexibility. Management has indicated
      plans to initiate a dividend program in FY2025, with an initial payout ratio of approximately 15-20%
      of net income.

  # Valuation
  - _target_:  nbprint.example.ExampleFinanceSectionHeading
    title: "Valuation Analysis"
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Our $10.00 price target is based on a blended valuation approach, incorporating three methodologies:
      P/E multiple, EV/EBITDA multiple, and discounted cash flow (DCF) analysis. We weight the P/E method
      at 40%, EV/EBITDA at 30%, and DCF at 30%, reflecting our confidence in the company's earnings
      visibility and the comparability of peer multiples.

  - _target_:  nbprint.example.ExampleFinanceValuationTable
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      For our P/E-based valuation, we apply a 12.5x multiple to our FY2025 EPS estimate of $0.90. This
      multiple represents a modest premium to the peer group average of 11.2x, which we believe is
      justified by ABCD's superior growth profile and return on equity. The company's three-year forward
      revenue CAGR of 15% compares favorably to the peer average of 8%, while its projected FY2025 ROE
      of 18.9% exceeds the peer median of 14.5%.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Our EV/EBITDA analysis applies an 8.5x multiple to FY2025E EBITDA of $2.56 billion, yielding a
      valuation of approximately $10.50 per share. This multiple is in line with the peer group median
      and reflects the company's strong cash generation characteristics and moderate leverage profile.
      We note that best-in-class operators in the sector trade at 9-10x EV/EBITDA, suggesting potential
      upside to our base case if the company continues to execute well.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Our DCF analysis assumes a weighted average cost of capital (WACC) of 9.2% and a terminal growth
      rate of 3.0%. We project free cash flows over a ten-year period, incorporating our revenue and
      margin assumptions along with capital expenditure requirements of approximately 3.5% of sales.
      This methodology yields a value of $9.00 per share, providing a conservative anchor to our
      blended valuation.

  # Key Risks
  - _target_:  nbprint.example.ExampleFinanceSectionHeading
    title: "Key Risks to Our Investment Thesis"
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      While we maintain a positive outlook on ABCD Inc., investors should be aware of several key risks
      that could impact the company's performance and our investment thesis:

  - _target_:  nbprint.example.ExampleFinanceBulletPoints
    items:
      - "<strong>Competitive Intensity:</strong> The mobility sector is experiencing increased competition from both established automotive manufacturers entering the space and well-funded startups. Intensifying competition could pressure pricing and market share."
      - "<strong>Regulatory Changes:</strong> Changes in government incentives for sustainable transportation or new safety regulations could impact demand and increase compliance costs."
      - "<strong>Supply Chain Disruption:</strong> The company relies on a complex global supply chain for key components. Disruptions could impact production and margins."
      - "<strong>Technology Risk:</strong> Rapid technological change in the mobility sector could render existing products obsolete or require substantial R&D investments."
      - "<strong>Macroeconomic Sensitivity:</strong> Consumer discretionary spending is sensitive to economic conditions. A recession could significantly impact demand."
      - "<strong>Execution Risk:</strong> The company's growth strategy requires successful new product launches and international expansion, which carry inherent execution risks."

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Additionally, the company faces foreign exchange exposure from its international operations, with
      approximately 42% of revenues generated outside North America. A strengthening U.S. dollar could
      negatively impact reported results. The company partially hedges this exposure but remains subject
      to translation effects.

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      From a financial perspective, while the company's balance sheet is healthy, any significant
      debt-funded acquisitions could increase leverage and financial risk. Management has indicated
      openness to M&A opportunities, which could be value-accretive if executed well but also carry
      integration risks.

  # Business Highlights Section
  - _target_:  nbprint.example.ExampleFinanceSectionHeading
    title: "Recent Business Highlights"
    color: ${parameters.color}

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      ABCD Inc. has achieved several notable milestones in recent quarters that underscore the strength
      of its business model and market position:

  - _target_:  nbprint.example.ExampleFinanceBulletPoints
    items:
      - "<strong>Q3 FY2024 Results:</strong> Revenues of $3.6 billion exceeded consensus estimates by 4%, driven by stronger-than-expected Personal Mobility sales in North America and Europe."
      - "<strong>Product Innovation:</strong> Launch of the new X-Series mobility platform featuring advanced autonomous capabilities and extended range, receiving positive early reviews."
      - "<strong>Strategic Partnership:</strong> Announced collaboration with a leading technology company to develop next-generation vehicle connectivity and entertainment systems."
      - "<strong>International Expansion:</strong> Opened three new manufacturing and distribution facilities in Southeast Asia, positioning for accelerated growth in emerging markets."
      - "<strong>Sustainability Leadership:</strong> Achieved carbon-neutral operations across all North American facilities, ahead of the 2025 target."

  - _target_:  nbprint.example.ExampleFinanceSectionText
    text: |
      Management commentary on recent earnings calls has emphasized confidence in the company's ability
      to navigate near-term headwinds while maintaining investment in long-term growth initiatives. The
      company has reaffirmed FY2024 guidance and provided preliminary FY2025 targets that align with our
      expectations, suggesting a positive outlook for the business.

  # Page Break - Disclosures
  - _target_:  nbprint.ContentPageBreak

  - _target_:  nbprint.example.ExampleFinanceDisclosures
