---
debug: false
_target_: nbprint.Configuration
outputs:
  _target_: nbprint.NBConvertOutputs
  naming: "{{name}}"
  root: ./outputs
  target: "html"

parameters:
  _target_: nbprint.example.ExampleParameters
  string: "STRING"

context:
  _target_: nbprint.example.ExampleContext
  params:
    key1: item1
    key2: item2

page:
  _target_: nbprint.example.ExampleReportPage
  bottom_left:
    _target_: nbprint.example.ExampleLogoInFooter
  bottom_right:
    _target_: nbprint.PageRegion
  bottom:
    _target_: nbprint.PageRegion
    content:
      _target_: nbprint.PageRegionContent
      content: "'Example Report'"


content:
  - _target_: nbprint.ContentCode
    content: |
      nbprint_ctx.string = string

  - _target_: nbprint.example.ExampleCoverPageContent
    logo:
      _target_: nbprint.example.ExampleNBPrintLogo

    title: "A generic report"
    subtitle: "In this section we have some boilerplate stuff"

  - _target_: nbprint.ContentTableOfContents

  - _target_: nbprint.PandasDisplayConfiguration
  - _target_: nbprint.SeabornDisplayConfiguration
    palette: pastel

  - _target_: nbprint.ContentMarkdown
    content: |
      # Section One
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      ## Subsection One
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      ## Subsection Two
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      ### Sub Sub1
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      #### Sub Sub Sub3

      ##### Sub Sub Sub3

        * Item 1
        * Item 2
          1. Item 2a
          2. Item 2b

      [Link](www.google.com)

      *some* other **stuff**

      ```python
      print("Hello World!")
      ```
      > Block
      > Quotes

  - _target_: nbprint.ContentPageBreak

  - _target_: nbprint.example.ExampleMarkdownBlock
    # content: |
    #   # Performance
    #   Now some discussion of the performance, as well as some charts
    #   Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    #   ## A Chart
    #   A chart of some data
    #   Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - _target_: nbprint.ContentCode
    content: |
      %matplotlib inline
      import matplotlib.pyplot as plt
      import superstore as sup

      df = sup.timeseries(20, ncol=7)

      # add to context
      nbprint_ctx.df = df

      fig = plt.figure(1, clear=True, figsize=(12,8));
      ax = fig.add_subplot(111);

      _ = df.plot(ax=ax);
      _ = fig.text(.3, -.05, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n'
                            'sed do eiusmod tempor incididunt ut labore et dolore magna \n'
                            'aliqua. Ut enim ad minim veniam, quis nostrud exercitation \n'
                            'ullamco laboris nisi ut aliquip ex ea commodo consequat. \n'
                            'Duis aute irure dolor in reprehenderit in voluptate velit.',
                fontsize=12,
                wrap=True,
                ha='left');
      _ = fig.text(.3, .06, 'This Image:',
                fontsize=12,
                weight='bold',
                wrap=True,
                ha='left');
      plt.show()

  - _target_: nbprint.ContentPageBreak

  - _target_: nbprint.ContentMarkdown
    content: |
      ## Some Widgets
      Some widgets, some ipywidgets and perspective

  - _target_: nbprint.ContentCode
    content: |
      from ipywidgets import IntSlider
      IntSlider()

  - _target_: nbprint.ContentCode
    content: |
      from perspective.widget import PerspectiveWidget
      PerspectiveWidget(nbprint_ctx.df)

  - _target_: nbprint.ContentMarkdown
    content: |
      ## A Grid
      And A grid of the data
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - _target_: nbprint.example.ExampleCodeBlock

