---
# global config options
debug: false
# end global config options

resources:

outputs:
  _target_:  nbprint.NBConvertOutputs
  path_root: ./outputs
  target: "html"

parameters:
  _target_:  nbprint.example.ExampleNewsParameters

context:
  _target_:  nbprint.example.ExampleNewsContext

page:

content:
  - _target_:  nbprint.example.ExampleNewsHeadlineContent
    title: ""
    subtitle: ""
    date: "November 8, 2023 08:45 GMT"
