---
debug: false
outputs:
  _target_:  nbprint.NBConvertOutputs
  naming: "{{name}}"
  root: ./outputs
  target: "html"

context:
  _target_:  nbprint.example.ExampleResearchReferencesContext

content:
  - _target_:  nbprint.example.ExampleResearchHeader
    content:
      - _target_:  nbprint.example.ExampleResearchTitle
        title: "An Example Research Publication Title"

      - _target_:  nbprint.example.ExampleResearchAuthors
        content:
          - _target_:  nbprint.example.ExampleResearchAuthor
            name: John Smith
            email: john.smith@columbia.edu
          - _target_:  nbprint.example.ExampleResearchAuthor
            name: Jane Doe
            email: jane.doe@columbia.edu
          - _target_:  nbprint.example.ExampleResearchAuthor
            name: Joe Schmo
            email: joe.schmo@columbia.edu

  - _target_:  nbprint.example.ExampleResearchBody
    content:
      - _target_:  nbprint.example.ExampleResearchSectionTitle
        title: Abstract
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionTitle
        title: 1. Introduction
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.ContentCode
        content: |
          %matplotlib inline
          import pandas as pd
          import matplotlib.pyplot as plt
          import superstore as sup
          import seaborn as sns

          sns.set()


          df = pd.DataFrame(sup.getTimeSeriesData())

          # add to context
          nbprint_ctx.df = df

          fig = plt.figure(1, clear=True, figsize=(12,8));
          ax = fig.add_subplot(111);

          _ = df.plot(ax=ax);
          _ = fig.text(.3, -.05, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n'
                                'sed do eiusmod tempor incididunt ut labore et dolore magna \n'
                                'aliqua. Ut enim ad minim veniam, quis nostrud exercitation \n'
                                'ullamco laboris nisi ut aliquip ex ea commodo consequat. \n'
                                'Duis aute irure dolor in reprehenderit in voluptate velit.',
                    fontsize=12,
                    wrap=True,
                    ha='left');
          _ = fig.text(.3, .06, 'This Image:',
                    fontsize=12,
                    weight='bold',
                    wrap=True,
                    ha='left');
          plt.show()
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - _target_:  nbprint.example.ExampleResearchSectionText
        text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
