import { test, expect } from "@playwright/test";

/**
 * End-to-end visual regression: start from a notebook or YAML fixture, run
 * the full nbprint pipeline (via globalSetup in integration.setup.mjs),
 * then open the generated HTML in Chromium and take per-page screenshots.
 *
 * Unlike the hand-built HTML fixtures exercised by visual.spec.js, these
 * tests prove the full conversion pipeline — including overlays, section
 * routing, and section-level style defaults — produces stable visual
 * output.
 */

// Helper: wait for pagedjs to finish rendering
async function waitForPagedJS(page, timeout = 30000) {
  await page.waitForSelector(".pagedjs_pages", { timeout });
  await page.waitForTimeout(500);
}

// Helper: capture per-page screenshots and compare against baselines.
// The tolerance here is intentionally generous: baselines are generated on
// macOS and CI runs on Linux, where font hinting and anti-aliasing produce
// small (~3–6%) per-pixel differences even for identical layouts. These
// E2E tests are about catching layout regressions end-to-end (pages paginate,
// overlays/section-styles apply, no content drops), not pixel-perfect
// cross-platform rendering — which is covered by visual.spec.js.
async function screenshotPages(page, name, maxPages = Infinity) {
  const pages = await page.locator(".pagedjs_page").all();
  const limit = Math.min(pages.length, maxPages);
  for (let i = 0; i < limit; i++) {
    await expect(pages[i]).toHaveScreenshot(`${name}-page-${i + 1}.png`, {
      maxDiffPixelRatio: 0.1,
      timeout: 15000,
    });
  }
  return pages.length;
}

// Fixtures generated by the globalSetup. Each produces /outputs/<name>.html.
// The "source" column is documentation only — setup generates the HTML.
const FIXTURES = [
  // Notebook-first fixture (wraps nbprint/tests/files/e2e_notebook.ipynb).
  { name: "e2e_notebook", source: "ipynb", minPages: 1, maxPages: 6 },
  // Notebook-first examples from examples/ — exercise section routing,
  // runtime API, and embedded overlays.
  { name: "notebook-sections", source: "ipynb", minPages: 1, maxPages: 6 },
  { name: "notebook-runtime", source: "ipynb", minPages: 1, maxPages: 4 },
  { name: "notebook-overlays", source: "ipynb", minPages: 1, maxPages: 4 },
  // YAML-driven fixtures, representative subset to keep the run bounded.
  { name: "basic", source: "yaml", minPages: 1, maxPages: 6 },
  { name: "inline", source: "yaml", minPages: 1, maxPages: 6 },
];

test.describe("E2E visual regression — full pipeline", () => {
  test.describe.configure({ timeout: 120_000 });

  for (const { name, minPages, maxPages } of FIXTURES) {
    test(`${name} — per-page screenshots`, async ({ page }) => {
      const response = await page.goto(`/outputs/${name}.html`);
      if (!response || response.status() === 404) {
        test.skip(true, `${name}.html not found — was globalSetup run?`);
        return;
      }

      await waitForPagedJS(page, 60000);

      const pageCount = await screenshotPages(page, `e2e-${name}`, maxPages);
      expect(pageCount).toBeGreaterThanOrEqual(minPages);
    });
  }
});
